---
title: "Abstract"
output: html_notebook
---


<!-- Nature abstract formula -->
<!-- - basic intro to field, for any scientist -->
<!-- - detailed background, for scientist in related field (1-2sent) -->
<!-- - problem address in paper (1-2sent) -->
<!-- - main result (1-2sent) -->
<!-- - addition to previous knowledge (1-2sent) -->
<!-- - result in general context -->


<!-- Outline -->
<!-- - state of urban agriculture, urban soils, but can promote food justice -->
<!-- - trade-offs among till and cover crop use... -->
<!-- - urban growers have limited resources and evidence-based strategies forward -->
<!-- - roto-till improved infiltration, tractor-till increased weeds -->
<!-- - weed suppression -->
<!-- - suggests no-till highlights more specific cover crop functions, and roto-till may be better than tractor-till for infiltration alongside compaction without more weeds -->
<!-- - details different strategy benefits for urban soils and urban growers -->


Urban soils have been degraded by decades of industrial activities, but they also represent opportunities to improve food sovereignty for urban residents practicing urban agriculture.
Urban growers often use varying practices of compost, tillage, and cover cropping, yet further integrated approaches could facilitated by model analyses of how different practices may compare or complement each other.
This study examined how tillage methods representing various intensities and cover crop mixes targeting different functions affected agricultural variables including soil strength, water infiltration rate, herbaceous weedy plant pressure, and crop yield in an urban Technosol in Detroit, MI, USA. 
Results showed that both roto- and tractor-till significantly lowered soil strength by *~50%* overall but not yield when compared to no-till, and roto-till also improved infiltration by *~15%*, while tractor-till reached deeper soils but allowed *~7%* denser weed growth.
Mixing sorghum-sudangrass, buckwheat, and cowpea cover crops significantly reduced weed density by *~50%* compared to other mixtures, and perennials appeared to increase depth to hardpan by *~2.5 cm (~17%)* but not affect soil water infiltration under no-till.
These results reveal that medium-intensity tillage may offer more balanced trade-offs for lowering soil strength, promoting infiltration, and feasibly minimizing weeds, and that cover crops can help reduce weeds under low-till strategies.
Overall this study offers evidence detailing effects of various tillage and cover crop styles that can be of use for smallholder urban growers.
