---
title: "Introduction"
output: 
  # html_notebook
  bookdown::pdf_document2: 
    toc: FALSE
bibliography: ../../library.bib
link-citations: TRUE
---


<!-- # Outline -->

<!-- - urban soils -->
<!-- - tilling -->
<!-- - cover cropping [mixes] -->
<!-- - this study -->


Urban soils have the potential to improve the livelihoods of most of the world *[@acuto18]* via implications for climate adaptation, erosion and storm-water runoff management, and local forestry *[@pavao-zuckerman08]*, but many urban soils are in poor health for cultivation after decades of industrial use, including sealing and structural engineering *[@lal15]*.
This is especially notable in post-industrial cities of the mid-western USA, where many vacant lots remain on soils can have relatively high compaction, pH, and chemical contamination *[@beniston16]*.
Degraded urban soils with low organic matter are also likely far from organic carbon saturation *[@stewart07]*, making the potential benefit from tailored agricultural management large *[@kumar16; @kuzyakov19]*.
However, popular single strategies like organic compost amendments to urban gardens, while widely beneficial across many physical, chemical, and biological properties *[@cogger05]*, can also have other side effects like excess phosphorus *[@small19]*, which highlights the benefits of new and ongoing research studies of urban soil management, especially of integrated approaches for soil multi-functionality *[@blesh17]* including cover cropping, tillage, diverse mulching, and others.
In response to various needs, urban agriculture continues to expand as local communities and non-profit organizations revitalize and establish a diversity of new green initiatives including landscaping to improve local access to healthy food and a cleaner and safer environment *[@block12; @clendenning16; @garcia-sempere19; @siebert20]*. 
Urban growers in particular often invest relatively large amounts of money, time, and resources from accessible capital into amending soils for vegetable production *(pers. comms.)*, 
thereby improving the potential impact of research for promising accessible urban soil remediation strategies, which appears to remain limited beyond compost *[@grossman03]*.

Mechanized tilling has long been a regular strategy improve short-term arability, among others like adding compost, although research studies increasingly report soil degradation after long-term and intensive tillage.
Short-term tillage benefits include larger soil pores and lower soil bulk density *[@hill85; @badalikova10]*, and potentially more available nutrients *[@wolkowski90]* with less potential weed regeneration *[@barberi01; @cordeau20]*, making tillage useful against soil compaction and associated water infiltration and drainage issues, which can facilitate faster seeding and crop establishment early in the season *[@monti01]*.
However, longer-term side effects of excessive and/or very intensive tillage include weaker soil aggregate stability and structure *[@six02a; @catania18]*, increasing dependence on tillage to maintain past yields *[@decarcer19]*, and faster soil erosion *[@richter21]*, which has more recently led to events like the USA Dust Bowl, and historically poses an existential threat to agricultural societies when combined with other stressors *[@lal07; @montgomery07; @amundson15]*.
In response, sustainable and regenerative agriculture theories promote no-till or minimal-till management approaches like broadfork tools to re-focus on soil health and fertility *[@wang06; @roger-estrade10]*, which comes with different challenges like stronger pressure from weeds *[@anderson07]*, highlighting a role for continuing research into diverse no-till strategies.
For urban growers, machinery can also be cost-prohibitive, and limited access to agricultural loans *[@daniel07]* has resulted in affected communities adapting by organizing equipment sharing systems, which can be more practical in denser urban housing arrangements compared to diffuse rural ones.
This variation in accessibility of machinery can promote mixed tillage strategies by urban growers including tractor- and/or roto-till, which likely have different effects on soil and weed issues, but there remains little public documentation comparing benefits of various tillage styles on remediating urban soils *[@bazzoffi98; @materechera09]*, which slows the innovation of tailored management strategies for the array of urban grower goals.

Cover cropping has been another long-recommended strategy of sustaining longer-term yields by maintaining soil fertility *[@perez21; @richter21]*, although current strategies could be improved from relying on single species to designing complementary species mixes.
The namesake benefit of cover crops is to cover the soil in areas without active cultivation, which maintains root activity and weakens erosion *[@garcia-gonzalez18]*, but different species will also vary in the benefits they can provide based on physiological traits.
For example, legumes like cowpea (or black-eyed peas, *`r taxize::comm2sci("black-eyed pea")[[1]]`*), clovers (*Trifolium sp.*), and hairy vetch (*`r taxize::comm2sci("hairy vetch")[[1]]`*) are popular cover crops because of their additional symbioses with root bacteria that fix nitrogen from the air into soils where it is more available for future crop use *[@grossman05]*.
Similarly, buckwheat helps scavenge soil phosphorus *[@possinger13]*, which is often a limiting macro-nutrient in clay soils *[@mori22]*, and could also be combined with compost that is usually high in phosphorus to address recurring soil phosphorus deficiencies.
Other plants, including grasses like sorghum (*`r taxize::comm2sci("sorghum")[[1]]`*), tend to grow deep roots, or have other traits like allelopathic chemical defenses, that compete with weeds enough to keep them suppressed over time *[@weston89]*.
Broader implications of cover cropping also include higher soil organic matter, though the underlying processes remain complex *[@king20]*, and few studies show direct correlations between soil organic matter and yield *[@oldfield19]*.
Furthermore, while large rural organic farms can benefit from incorporating specifically-chosen cover cropping into their mechanized operations, the reliance of urban agriculture more on labor over machinery offers an opportunity to develop new cover cropping systems that combine seeding and terminating different species together to improve the potential efficiency of soil remediation efforts.
For example, sorghum, cowpea, and buckwheat could be combined into a mixed strategy that can increase soil nitrogen, soil phosphorus, and suppress weeds via deep and shallow roots with allelopathic chemical defenses, although cover crop synergisms generally remain understudied *[@mead81; @bedoussac15; @bourke21]*.
An integrated complex approach to optimizing cover cropping systems including interspecific species interactions are well-posed to be validated by research studies in urban agriculture followed by adaptation to rural agriculture, and even international implications *[@stewart13]*.

In this study, we investigated how different tillage techniques and cover crop species mixes affect soil physical properties and yield.
Tillage methods ranged from high disturbance using a tractor and implements to minimal disturbance with a broadfork. 
Cover crop species mixes were selected based on target functions including reducing compaction, suppressing weeds, and perenniality, or potential for sustainable re-growth. 
We hypothesized that both tillage and cover crop mixing would confer similar benefits to soil functions, which would translate to weed pressure and yield.
Accordingly, we predicted that roto-till, a moderate soil disturbance, would best balance compaction and weed pressure benefits, deepening where soil hardpan layers occur that limit root penetration, and thereby increase soil water infiltration rates, and also reduce weed cover, density, and diversity. 
We also expected that the cover crop mix designed against soil compaction would have the deepest soil harpan depth and highest water infiltration rates compared to other mixes, mostly due to the deeper rooting potential by forage radish (*`r taxize::comm2sci("radish")[[1]]` var. longipinnatus*) and ryegrass (*Secale cereale*).
Finally we expected that the cover crop mix designed for weed suppression would experience the lowest local weed cover, density, and diversity, due to allelopathic chemical defense traits from buckwheat (*Fagoprum esculentum*) and surghum-sudangrass (*`r taxize::comm2sci("sorghum")[[1]]` x `r taxize::comm2sci("sorghum")[[1]]` var. sudanese*).
